/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.hrivero.flink.kafka;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    public void appHasAGreeting() {
        
        assertNotNull("app should have a greeting", "");
    }
}
